---
title: "w3-notes"
author: "Spencer Zhang"
date: "1/20/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)
library(mapboxapi)
```

```{r g-drive-path}
# #define path for accessing your G drive
# 
# path <- "G:/..." 
# #windows users
# 
# path_mac <- "/Volumes/GoogleDrive/..."
# #mac users
# 
# eg_file <- read.csv(paste0(path, "filename.csv"))

path <- "/Volumes/GoogleDrive/Shared drives/SFBI/Data Library"
```

```{r data-loading}
pois <- st_read("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/OSM/gis_osm_pois_a_free_1.shp")
```

```{r}
pois_summary <- pois %>% 
  st_drop_geometry() %>% 
  group_by(fclass) %>% 
  count() %>% 
  arrange(desc(n)) #reorder by number of counts in a fclass unique value
```

```{r}
smc_boundary <- counties("CA") %>% 
  filter(NAME == "San Mateo") %>% 
  st_transform(st_crs(pois))

smc_pois <- pois %>% 
  .[smc_boundary, ] %>% 
  rename(amenity = fclass)
```

```{r}
mapview(smc_pois, zcol = "amenity")
```

```{r}
smc_pois_filter <- smc_pois %>% 
  filter(amenity %in% c(
    "park",
    "convenience",
    "restaurant",
    "supermarket",
    "library"
  ))

mapview(smc_pois_filter, zcol = "amenity")
```

```{r}
smc_cbgs <- block_groups("CA","San Mateo")

nfo_boundary <- places("CA") %>% 
  filter(NAME == "North Fair Oaks")

nfo_cbgs <- smc_cbgs %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(smc_cbgs %>% select(GEOID)) %>% 
  st_as_sf()

mapview(nfo_cbgs)
```

```{r mapbox-token}
devtools::install_github("walkerke/mapboxapi")

library(mapboxapi)

# mb_access_token("sk.eyJ1Ijoic3BlbmNlcnoiLCJhIjoiY2t5cDMwbHZ4MDY0cjJvb3k3MWx4ZmZqNCJ9.BvoXo88c-qPxB2FNKEV0Vg", install = T)

readRenviron("~/.Renviron")
```


```{r}
isochrone <- mb_isochrone(
  nfo_cbgs,
  profile = "walking",
  time = c(5,10,15)
)
```

```{r}
isochrone[1:3,] %>% mapview()
```

```{r}
isochrones <- c("walking","driving") %>% 
  map_dfr(function(x){
    
    mb_isochrone(
      nfo_cbgs,
      profile = x,
      time = c(5,10,15)
    ) %>% 
      mutate(mode = x)
    
  })
```
```{r}
saveRDS(isochrones, "nfo_isochrones.rds")
isochrones <- readRDS("nfo_isochrones.rds")
```


```{r}
access_raw <- isochrones %>% 
  st_make_valid() %>% 
  st_join(smc_pois_filter) %>% 
  st_drop_geometry() %>% 
  filter(!is.na(osm_id))
```

```{r}
amenity_pref <- data.frame(
  amenity = c("park", "convenience", "restaurant", "supermarket", "library"),
  amenity_value = c(0.8,0.5,0.25,1,0.7),
  amenity_quant = c(2,5,30,1,1)
) %>%
  mutate(
    amenity_decay = -log(0.5)/amenity_quant
  )
```

```{r}
amenity_preference <- data.frame(
  amenity = c(
    "park",
    "convenience",
    "restaurant",
    "supermarket",
    "library"
  ),
  amenity_value = c(
    0.8,
    0.6,
    0.25,
    1,
    0.7
  ),
  amenity_quantity = c(
    2,
    5,
    30,
    1,
    1
  )
) %>% 
  mutate(
    amenity_decay = -log(0.5)/(amenity_quantity)
  )

mode_preference <- data.frame(
  mode = c(
    "walking",
    "biking",
    "driving"
  ),
  mode_value = c(
    1,
    0.7,
    0.5
  ),
  mode_reasonable = c(
    15,
    10,
    20
  )
) %>% 
  mutate(
    mode_decay = -log(0.5)/mode_reasonable
  )
```

```{r}
complete_temp <- access_raw %>% 
  left_join(
    amenity_preference,
    by = "amenity"
  ) %>% 
  left_join(
    mode_preference,
    by = "mode"
  ) %>% 
  group_by(id,mode,amenity) %>% 
  arrange(time) %>%
  mutate(
    amenity_rank = row_number() -1
  ) %>%
  ungroup()
```

```{r}
complete_mode <- complete_temp %>%
  mutate(
    score = amenity_value * exp(-amenity_rank * amenity_decay) * exp(-time * mode_decay)
  ) %>%
  group_by(id, mode) %>%
  arrange(desc(score)) %>%
  filter(!duplicated(osm_id)) %>%
  summarize(
    score = sum(score, na.rm = T)/sum(complete_baseline$score)
  )
```

```{r}
view(complete_mode)
#how do you interpret the scores?
#- compare with a baseline
```

# baseline score construction
```{r}
complete_baseline <- data.frame(
  amenity = amenity_preference$amenity %>%
    rep(., amenity_preference$amenity_quantity)
) %>%
  left_join(amenity_preference) %>%
  group_by(amenity) %>%
  mutate(
    amenity_rank = row_number() - 1
  ) %>%
  ungroup() %>%
  mutate(
    score = amenity_value *exp(-amenity_rank*amenity_decay) * 0.5
  ) #0.5 represents all amenity are within reasonable range of prefered mode -- baseline definition, so no mode decay is needed
```

```{r}
sum(complete_baseline$score) #5.42802 baseline score total
```




